project:
  type: website
  output-dir: C:\Users\zj1026.stu\OneDrive - UBC\FCOR599\Term2\Guest Lecture\GuestLec3-E Portfolio\E-Portfolio

website:
  title: "Welcome to My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: map_gallery.qmd
        text: Map Gallery
      
      - text: Projects
        menu:
          - href: content1.qmd
            text: Project 1 – Evaluating and comparing the performance of VRI data and LiDAR-derived stand metrics across different geospatial features in MKRF, BC
          - href: content2.qmd
            text: Project 2 – Remote Sensing Used in Smart Urban Settings​

      - href: contact.qmd
        text: Contact Info
        

format:
  html:
    theme:
      light: lumen
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    smooth-scroll: true
    fontsize: 1.1em
    linestretch: 1.7
    code-fold: true
    code-tools: true
    highlight-style: github
    anchor-sections: true
    respect-user-color-scheme: true

    

    
editor: visual

