---
title: "Resume"
format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "On this page"
    toc-depth: 3
---


<h2>Project Experiences</h2>

-   ::: fw-semibold
    [Project 1: Evaluating and Comparing the Performance of VRI Data and LiDAR-derived Stand Metrics across Different Geospatial Features in MKRF, BC]{.text-primary} 
    :::
    
    ::::: columns
    ::: {.column width="30%"}
    [View Project 1](content_1.html){.project-link}
    :::

    ::: {.column width="5%"}
    :::

    ::: {.fst-italic .text-muted .text-end .column width="65%"}
    *September 2025 – April 2026*
    :::
    :::::


    <ul class="mt-2 mb-0">

    <li>Process LiDAR point clouds using R, then calculate various stand metrics and geophysical metrics using either R or ArcGIS Pro.</li>
    
    <li>Employ statistical methods in R to compute, summarize, and analyze errors in each stored VRI polygon dataset.</li>
    
    <li>Present research findings through multiple formats, including posters, videos, written reports, and academic presentations.</li>

    </ul>
    
    <br>
    
-   ::: fw-semibold
    [Project 2: Remote Sensing Used in Smart Urban Settings]{.text-primary} 
    :::

    ::::: columns
    ::: {.column width="30%"}
    [View Project 2](content_2.html){.project-link}
    :::

    ::: {.column width="5%"}
    :::

    ::: {.fst-italic .text-muted .text-end .column width="65%"}
    *September 2025 – December 2025*
    :::
    :::::

    <ul class="mt-2 mb-0">

    <li>Developed interactive dashboards and maps to visualize livability across the Greater Vancouver region using Python (folium, ipywidgets, branca).</li>
    
    <li>Served as project lead, structured outlines and timelines, arranged meetings, and integrated feedback.</li>
    
    <li>Assisted teammates in deriving pollution, greening, and temperature metrics from remote sensing data and integrating them with public datasets to compute livability scores across Dissemination Areas using ArcGIS Pro.</li>
    
    <li>Contributed to data processing, analysis, and final project presentation.</li>

    </ul>
    
    <br>
    
-   ::: fw-semibold
    [Project 3: Mapping Tree Species Across the Petawawa Research Forest Using LiDAR for Forest Inventories]{.text-primary} 
    :::
    
    ::::: columns
    ::: {.column width="30%"}
    [View Project 3](content_3.html){.project-link}
    :::

    ::: {.column width="5%"}
    :::

    ::: {.fst-italic .text-muted .text-end .column width="65%"}
    *September 2025 – December 2025*
    :::
    :::::


    <ul class="mt-2 mb-0">

    <li>Applied Random Forest classification using Python (sklearn), systematically evaluating spectral and topographic predictors.</li>
    
    <li>Lead the production of final maps, incorporating iterative feedback and revisions.</li>
    
    <li>Collaborated with team members via Google Colab for code sharing and Presentation.</li>

    </ul>
    
    <br>
    <br>
    

<h2>Education</h2>

::: fw-semibold
[Master of Geomatics for Environmental Management,]{.text-primary} UBC Faculty of Forestry, Vancouver, BC
:::

::: {.fst-italic .text-muted .text-end}
*Completion: 2026*
:::

<ul class="mt-2 mb-0">

Capstone Project: Evaluating and comparing the performance of current VRI data and LiDAR-derived stand metrics across different geospatial features in UBC’s MKRF, BC. ( detail see "Project Content")

</ul>

<br>

::: fw-semibold
[Bachelor of Arts,]{.text-primary} UBC Faculty of Arts, Vancouver, BC
:::

::: {.fst-italic .text-muted .text-end}
*Completion: 2025*
:::

<ul class="mt-2 mb-0">

Specialization: Geography, Environment & Sustainability.

</ul>

<br> <br>

<h2>Awards & Honors</h2>

-   Outstanding International Student Award of \$10,000, UBC (2021)
-   Faculty of Arts International Student Scholarship of \$5,500.00, UBC (2023)
-   Faculty of Arts International Student Scholarship of \$5,000.00, UBC (2024)

<br> <br>

<h2>Teaching Assistantships</h2>

-   ::: fw-semibold
    [CHIN131/231 Teaching assistant,]{.text-primary} UBC Department of Asian Studies, Vancouver, BC
    :::

    ::: {.fst-italic .text-muted .text-end}
    *May 2024 – April 2025*
    :::

    <ul class="mt-2 mb-0">

    <li>Attending weekly tutorial sessions.</li>

    <li>Developing and maintaining the course web pages; assisting in editing text materials.</li>

    <li>Assisting with the devising and participating in team meetings and events.</li>

    <li>Reviewing and commenting on student work weekly; reporting issues such as academic misconduct, technical errors, or missing material.</li>

    </ul>

<br>

-   ::: fw-semibold
    [CHIN405 OER,]{.text-primary} UBC Department of Asian Studies, Vancouver, BC
    :::

    ::: {.fst-italic .text-muted .text-end}
    *May 2024 – August 2024*
    :::

    <ul class="mt-2 mb-0">

    <li>Assist in designing web pages to incorporate course/instructor requirements into the web design</li>

    <li>Modify, maintain, and update course webpages</li>

    <li>Create web page tutorials, including written instructions and video recordings</li>

    </ul>

<br> <br>

<h2>Institutional Service</h2>

-   ::: fw-semibold
    [Assorted Farm Tasks, UBC Farm volunteer program,]{.text-primary} Vancouver, BC
    :::

    ::: {.fst-italic .text-muted .text-end}
    *May 2023 – June 2023*
    :::

    <ul class="mt-2 mb-0">

    <li>Promote the understanding of various crops, process and join the routine tasks for the crop growth.</li>

    <li>Handle detailed, tedious, and energy-consuming work, like weeding and harvesting strawberries, carrots, and lettuce.</li>

    </ul>
